[theme]
primaryColor="#7792E3"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"

[server]
enableXsrfProtection=false
enableCORS=false

[browser]
gatherUsageStats = false
